language: node_js
node_js:
  - "0.10"

addons:
  postgresql: "9.3"

install:
  - "bash scripts/install.sh -ipn"
  - "git submodule foreach --recursive 'git submodule init'"
  - "git submodule update --recursive"

before_script:
  - "source ~/.bashrc"
  - "npm install"
  - "mkdir lib/extensions"
  - "cd node-datasource"
  - "npm install"
  - "mkdir public/javascripts"
  - "../scripts/xcore build all"
  - "npm start &"
  - "sleep 10"
  - "cd .."

script:
  - "npm run-script test-build"
