#!/usr/bin/env node

// Load required libraries.
var _ = require('underscore');
var sys = require('sys');
var logger = require('winston');
var fs = require('fs');
var path = require('path');
var cp = require('child_process');
var spawn = cp.spawn;
var exec = cp.exec;
var args = require('minimist')(process.argv.slice(2));

// Enable color for the logger.
logger.remove(logger.transports.Console);
logger.add(logger.transports.Console, {colorize: true});

var getExtensionManifests = function() {
  var extensionDirs = fs.readdirSync(path.join(__dirname, '../lib/extensions')),
      manifests = {};

  _.each(extensionDirs, function(dir, idx, dirs) {
    if (dir == '.git') { return true; }
    try {
    var contents = fs.readFileSync(path.join(
      __dirname,'../lib/extensions', dir, '/database/source/manifest.js'), 'utf8'),
      manifest = JSON.parse(contents);

      manifests[manifest.name] = manifest;
    } catch (err) {
      logger.error(err);
    }
  });

  return manifests;
};

// Removes extension code from client.
var cleanup = function() {
  logger.info("Removing extension code from client.");

  var manifests = getExtensionManifests();

  _.each(manifests, function(manifest) {
    var clientCodeDir = path.join(__dirname, '../lib/extensions/', manifest.name, '/client');
    var dirs = fs.readdirSync(clientCodeDir);
    _.each(dirs, function (dir) {
      var extDir = path.join(__dirname, '../lib/client/source/', dir, manifest.name);
      exec('rm -rf ' + extDir);
    });

  });
};

var buildDatabase = function () { logger.info("Attempting to build database."); };

// Copies client code from the extensions into lib/client.
var copyClientCode = function (callback) {
  // Collect all the extension manifest and and sort by load order.
  logger.info("Copying extensions into client.");
  var manifests = getExtensionManifests(),
      buildPackageString = function (files) {
        var dependList = '';
        _.each(files, function (f) {
          if (f !== 'package.js') {
            dependList += '"'+f+'"';

            if (f !== _.last(files)) {
              dependList += ',';
            }

            dependList += '\n';
          }
        });
        return dependList;
      };

  _.each(manifests, function(manifest) {
    if(manifest.dependencies) {
      _.each(manifest.dependencies, function (depName) {
        var depManifest = manifests[depName];
        if(depManifest.loadOrder > manifest.loadOrder) {
          logger.error(
            "Extension '%s' has a load order of %s. It's dependent '%s' has a load order of %s. " +
            "Extensions can't have a lower load order than their dependencies.",
            manifest.name, manifest.loadOrder, depManifest.name, depManifest.loadOrder
          );
          process.exit(1);
        }
      });
    }
  });

  manifests = _.sortBy(manifests, 'loadOrder');

  _.each(manifests, function(manifest) {
    var clientCodeDir = path.join(__dirname, '../lib/extensions/', manifest.name, '/client');
    var dirs = fs.readdirSync(clientCodeDir);
    _.each(dirs, function (dir) {
      var extDir = path.join(__dirname, '../lib/client/source/', dir, manifest.name);

      exec('rm -rf ' + extDir, function (err, stdout, stderr) {
        if (err !== null) {
          logger.error(err);
          process.exit(1);
        }
        
        exec('cp -R ' + clientCodeDir + '/' + dir + ' ' + extDir,
          function(err2, stdout2, stderr2) {
            if (err2 !== null) {
              logger.error(err2);
              process.exit(1);
            }

            var newPackageJS = "enyo.depends(\n";
            var existingFiles = fs.readdirSync(path.join(__dirname, "../lib/client/source/", dir));
            var extensionFiles = fs.readdirSync(clientCodeDir + '/' + dir);

            // Copy the files that already exist back into the new package.js.
            newPackageJS += buildPackageString(existingFiles);

            newPackageJS += ");";

            // Tell enyo to depend on this code.
            var depFile = path.join(__dirname, "../lib/client/source/"+dir+"/package.js");
            fs.writeFileSync(depFile, newPackageJS);
          }
        );
      });
    });

  });

  callback();
};

/**
  * Link extension client code to enyo's lib folder then run the enyo deploy.sh
  * script. The compiled client code should be in the lib/client/build folder.
*/
var buildClient = function () {
  logger.info("Attempting to build client code.");

  // Copy the extension client code into lib/client.
  copyClientCode(function () {
    var deployScript = path.join(__dirname, '../lib/client/tools/deploy.sh');
    logger.info("Executing build...");
    spawn(deployScript, ['-T'], { stdio: 'inherit' });
  });
};

var buildAll = function () {
  buildDatabase();
  buildClient();
};

// Handle the command line arguments.
_.each(args._, function(arg, idx, argz) {
  switch(arg) {

    // Print usage information
    case 'help':
      console.log("Help & usage information will go here.");
      process.exit(0);

    // Print the xCore version
    case 'version':
      // Grab the version number from the package.json file.
      var packageJson = fs.readFileSync(path.join(__dirname, "../package.json"));
      console.log("Version: " + JSON.parse(packageJson).version);
      process.exit(0);

    // Build the client, database or both.
    case 'build':
      toBuild = argz[idx+1];

      switch(toBuild) {
        case 'all':
          buildAll();
          break;
        case 'client':
          buildClient();
          break;
        case 'database':
          buildDatabase();
          break;
      }
  }

});
