#!/usr/bin/env node

// Author: Christopher Rankin
// Copyright: 2014 Pangea Real Estate

var _							= require('underscore'),
		async					= require('async'),
		fs						= require('fs'),
		path					=	require('path'),
		args					= require('minimist')(process.argv.slice(2)),
		buildDatabase = require('./lib/xcore/database').buildDatabase,
		buildClient		= require('./lib/xcore/client').buildClient,
		xTest					= require('./lib/xcore/test'),
    extension     = require('./lib/xcore/extension'),
		logger				= require('./lib/xcore/logger').logger;


if (args._.length > 0) {
	// Handle the command line arguments.
	_.each(args._, function(arg, idx, argz) {
	  switch(arg) {
	
	    // Print usage information
	  case 'help':
	    console.log("Help & usage information will go here.");
	    break;
	    
	    // Print the xCore version
	  case 'version':
	    // Grab the version number from the package.json file.
	    var packageJson = fs.readFileSync(path.join(__dirname, "../package.json"));
	    console.log("Version: " + JSON.parse(packageJson).version);
	    break;
	    
	  // Build the client, database or both.
	  case 'build':
	    toBuild = argz[idx+1];
	    
	    switch(toBuild) {
	      case 'all':
					// buildDatabase();
					// buildClient();
	        break;
	      case 'client':
	        buildClient();
	        break;
	      case 'database':
					buildDatabase(args);	
	        break;
				default:
					console.log("// TODO: Print build usage");
					process.exit(0);
	    }
	
	    break;
    	    
	  case 'test':
	    toTest = argz[idx+1];
	    
	    if (toTest == 'all') {
	      xTest.testAll();
	    } else {
	      xTest.testExtension(toTest);
	    }    
			break;

    case 'new':
      var type = argz[idx + 1],
          name = argz[idx + 2];
    
      switch(type) {
        case 'extension':
          extension.generateExtension(name);
          break;
      }
      break;
    }
    
	
	});
} else {
	console.log("Print xcore usage.");
}
